default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mojo_development

test:
  <<: *default
  database: mojo_test

production:
  <<: *default
  database: mojo_production